Category:
    type: object
    config:
        description: "A category"
        resolveField: '@=resolver("App\\GraphQL\\Resolver\\CategoryResolver", [info, value, args])'
        fields:
            id:
                type: "Int!"
                description: "The unique ID of the category."
            name:
                type: "String"
                description: "Category name."
            items:
                type: ItemConnection
                argsBuilder: Relay::ForwardConnection
