Mutation:
    type: object
    config:
        fields:
            createCatalog:
                type: Category
                args:
                    name:
                        type: String!
                resolve: "@=mutation('category_create', [args['name']])"
            createItem:
                type: Item
                args:
                    category:
                        type: Int!
                    name:
                        type: String!
                    price:
                        type: Float!
                resolve: "@=mutation('item_create', [args['category'], args['name'], args['price']])"
            addToBasket:
                type: Basket
                args:
                    item:
                        type: Int!
                        description: 'Item id.'
                    amount:
                        type: Int!
                        description: 'Amount of the item, to be added'
                resolve: "@=mutation('basket_add', [args['item'], args['amount']])"
            removeFromBasket:
                type: Basket
                args:
                    item:
                        type: Int!
                        description: 'Item id, to be removed.'
                resolve: "@=mutation('basket_remove', [args['item']])"
            payment:
                type: Transaction
                resolve: "@=mutation('transaction_create')"
