Mutation:
    type: object
    config:
        fields:
            createCatalog:
                type: Category
                args:
                    name:
                        type: String!
                resolve: "@=mutation('category_create', [args['name']])"
            createItem:
                type: Item
                args:
                    category:
                        type: Int!
                    name:
                        type: String!
                    price:
                        type: Float!
                resolve: "@=mutation('item_create', [args['category'], args['name'], args['price']])"
