Mutation:
    type: object
    config:
        fields:
            createCatalog:
                type: Category
                args:
                    name:
                        type: String!
                resolve: '@=mutation("App\\GraphQL\\Mutation\\CategoryMutation::create", [args["name"]])'
            createItem:
                type: Item
                args:
                    name:
                        type: String!
                    price:
                        type: Float!
                resolve: '@=mutation("App\\GraphQL\\Mutation\\ItemMutation::create", [args["name"], args["price"]])'
