Query:
    type: object
    config:
        fields:
            getCategory:
                type: Category
                args:
                    id:
                        type: Int!
                resolve: "@=resolver('category_get', [args['id']])"
            getItem:
                type: Item
                args:
                    id:
                        type: Int!
                resolve: "@=resolver('item_get', [args['id']])"
            getBasket:
                type: Basket
                resolve: "@=resolver('basket_get')"
            getTransaction:
                type: Transaction
                args:
                    id:
                        type: Int!
                        description: Transaction ID.
                resolve: "@=resolver('transaction_get')"

            getAuthToken:
                type: String
                args:
                    username:
                        type: String!
                    password:
                        type: String!
                resolve: "@=resolver('item_get_collection', [args['username'], args['password']])"
            getCatalogs:
                type: "[Category]"
                resolve: "@=resolver('category_get_collection')"
            getItems:
                type: "[Item]"
                args:
                    id:
                        type: Int!
                        description: Category ID.
                resolve: "@=resolver('item_get_collection', [args['id']])"
            getTransactions:
                type: "[Transaction]"
                args:
                    id:
                        type: Int!
                        description: User ID.
                resolve: "@=resolver('transaction_get_collection', [args['id']])"
