Query:
    type: object
    config:
        fields:
            getCategory:
                type: Category
                args:
                    id:
                        type: Int
                resolve: '@=resolver("App\\GraphQL\\Resolver\\CategoryResolver::resolve", [args["id"]])'
            getItem:
                type: Item
                args:
                    id:
                        type: Int
                resolve: '@=resolver("App\\GraphQL\\Resolver\\ItemResolver::resolve", [args["id"]])'
