Query:
    type: object
    config:
        fields:
            getCategory:
                type: Category
                args:
                    id:
                        type: Int!
                resolve: "@=resolver('category_get', [args['id']])"
            getItem:
                type: Item
                args:
                    id:
                        type: Int!
                resolve: "@=resolver('item_get', [args['id']])"
            getBasket:
                type: Basket
                args:
                    showBasket:
                        type: Boolean
                resolve: '@=resolver("App\\GraphQL\\Resolver\\BasketResolver::resolve", [args["showBasket"]])'

            getAuthToken:
                type: String
                args:
                    username:
                        type: String!
                    password:
                        type: String!
                resolve: '@=resolver("App\\GraphQL\\Resolver\\UserResolver::getAuthToken", [args["username"], args["password"]])'
            getCatalogs:
                type: "[Category]"
                args:
                    showCategories:
                        type: Boolean
                resolve: '@=resolver("App\\GraphQL\\Resolver\\CategoryResolver::getCollection", [args["showCategories"]])'
            getItems:
                type: "[Item]"
                args:
                    categoryId:
                        type: Int!
                resolve: '@=resolver("App\\GraphQL\\Resolver\\ItemResolver::getCollection", [args["categoryId"]])'
