Category:
    type: object
    config:
        description: "A category"
        fields:
            id:
                type: "Int!"
                description: "The unique ID of the category."
            name:
                type: "String"
                description: "Category name."
